import java.util.HashMap;
import java.util.List;
import java.util.Map;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
  private ItemRepository itemRepository;
  private SalesPromotionRepository salesPromotionRepository;

  public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
    this.itemRepository = itemRepository;
    this.salesPromotionRepository = salesPromotionRepository;
  }

  public String bestCharge(List<String> inputs) {
    //TODO: write code here
    StringBuilder sb = new StringBuilder();
    List<Item> items = itemRepository.findAll();
    List<SalesPromotion> promotions = salesPromotionRepository.findAll();
    int originalPrice = 0;
    sb.append("============= 订餐明细 =============\n");
    Map<Item, Integer> orderedMap = new HashMap<>();
    for (String input : inputs) {
      String[] strs = input.split(" ");
      for (Item item : items) {
        if (item.getId().equals(strs[0])) {
          orderedMap.put(item, Integer.parseInt(strs[2]));
          int price = (int) item.getPrice() * Integer.parseInt(strs[2]);
          sb.append(item.getName() + " x " + strs[2] + " = " + price + "元\n");
          originalPrice += price;
        }
      }
    }
    sb.append("-----------------------------------\n");
    int one = originalPrice >= 30 ? 6 : 0, two = 0;
    for (Item item : orderedMap.keySet()) {
      if (promotions.get(1).getRelatedItems().contains(item.getId())) {
        two += (int) (item.getPrice() / 2) * orderedMap.get(item);
      }
    }
    if (one == 0 && two == 0) {
      sb.append("总计：" + originalPrice + "元\n");
    } else if (one >= two) {
      sb.append("使用优惠:\n");
      sb.append(promotions.get(0).getDisplayName());
      sb.append("，省" + one + "元\n");
      sb.append("-----------------------------------\n");
      sb.append("总计：" + (originalPrice - one) + "元\n");
    }else {
      sb.append("使用优惠:\n");
      sb.append(promotions.get(1).getDisplayName() + "(");
      for (Item item : orderedMap.keySet()) {
        if (promotions.get(1).getRelatedItems().contains(item.getId())) {
          sb.append(item.getName() + "，");
        }
      }
      sb.deleteCharAt(sb.length() - 1);
      sb.append(")");
      sb.append("，省" + two + "元\n");
      sb.append("-----------------------------------\n");
      sb.append("总计：" + (originalPrice - two) + "元\n");
    }
    sb.append("===================================");
    return sb.toString();
  }
}
